#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

insmod /lib/modules/5.4.61/extra/8189fs.ko
ifconfig wlan0 up 
# wpa_supplicant -B -d -i wlan0 -c /etc/wpa_supplicant.conf
# udhcpc -i wlan0

